/*
 * Buzzchat CPOO Server API
 * This is a prototype of CPOO's BuzzChat front/back API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: aymane.menfaa@insa-rennes.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import okhttp3.Cookie;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import org.apache.http.HttpStatus;
import org.junit.Assert;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.model.ResponseEntity;
import org.openapitools.client.model.UserCredentialsDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * API tests for AuthenticationApi
 */

public class AuthenticationApiTest {

  private final AuthenticationApi api = new AuthenticationApi();
  private MonCookieJar MonCookie;
  private List<Cookie> cookies;



  @BeforeEach
  public void init() throws ApiException {
    MonCookie = new MonCookieJar();

    // Simulate the behavior of a web browser by remembering cookies set by the server
    OkHttpClient.Builder builder = new OkHttpClient.Builder();
    OkHttpClient okHttpClient = builder.cookieJar(MonCookie).build();
    ApiClient apiClient = new ApiClient(okHttpClient);
    api.setApiClient(apiClient);
  }



  @Test
  public void signinTest() throws ApiException {
    UserCredentialsDTO userCredentialsDTOvalide = new UserCredentialsDTO();
    userCredentialsDTOvalide
      .login("hamza")
      .password("pwd")
      .email("hamza@buzzchat.com")
      .dateDeNaissance("26/02/2002")
      .prenom("Hamza")
      .nom("Azer")
      .photo("assets/photo.png");

    UserCredentialsDTO userCredentialsDTOinvalide = new UserCredentialsDTO();
    userCredentialsDTOinvalide
      .login("noha")
      .password("pwd")
      .email("noha@buzzchat.com")
      .dateDeNaissance("26/02/2002")
      .prenom("Noha")
      .nom("Doaif")
      .photo("assets/photo.png");
    try {
      ResponseEntity response = api.signin(userCredentialsDTOinvalide);
      Assertions.fail();
    }catch(ApiException e){
      Assertions.assertEquals(HttpStatus.SC_UNAUTHORIZED, e.getCode());
    }

    api.signup(userCredentialsDTOvalide);
    api.signin(userCredentialsDTOvalide);

    try {
      ResponseEntity response2 = api.signin(userCredentialsDTOvalide);
      Assertions.fail();
    }catch (ApiException e) {
      Assertions.assertEquals(HttpStatus.SC_CONFLICT, e.getCode());
    }

    api.signout();

  }



  @Test
  public void signoutTest() throws ApiException {
    // Inscrire un nouvel utilisateur (s'il n'existe pas déjà)
    UserCredentialsDTO userCredentialsDTO = new UserCredentialsDTO()
      .login("zakaria")
      .password("pwd")
      .email("zakaria@buzzchat.com")
      .dateDeNaissance("26/02/2002")
      .prenom("Zakaria")
      .nom("Ehd")
      .photo("assets/photo.png");

    try {
      api.signup(userCredentialsDTO);
    } catch (ApiException e) {
      // Gérer l'exception (par exemple, vérifier si l'utilisateur existe déjà)
    }

    // Connectez-vous avec les informations de l'utilisateur
    api.signin(userCredentialsDTO);

    // Maintenant, vous pouvez appeler signout
    try {
      api.signout();
    } catch (ApiException e) {
      Assertions.assertEquals(HttpStatus.SC_NO_CONTENT, e.getCode());
    }
  }




  @Test
  public void signupTest() throws ApiException {
    UserCredentialsDTO userCredentialsDTO = new UserCredentialsDTO()
      .login("aymane")
      .password("pwd")
      .email("aymane@buzzchat.com")
      .dateDeNaissance("26/02/2002")
      .prenom("Aymane")
      .nom("Menfaa")
      .photo("assets/photo.png");
    ResponseEntity response = api.signup(userCredentialsDTO);
    try {
      ResponseEntity response2 = api.signup(userCredentialsDTO);
    }catch(ApiException e){
      Assertions.assertEquals(HttpStatus.SC_CONFLICT, e.getCode());
    }
    api.signin(userCredentialsDTO);
    api.signout();
  }

}
