/*
 * Buzzchat CPOO Server API
 * This is a prototype of CPOO's BuzzChat front/back API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: aymane.menfaa@insa-rennes.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import okhttp3.OkHttpClient;
import org.apache.http.HttpStatus;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.model.UserCredentialsDTO;
import org.openapitools.client.model.UserProfileDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * API tests for UserApi
 */

public class UserApiTest {

    private final UserApi api = new UserApi();
    private final AuthenticationApi apiAuth = new AuthenticationApi();
    private MonCookieJar MonCookie;

    private UserCredentialsDTO user1 = new UserCredentialsDTO()
      .login("aymane")
      .password("pwd")
      .email("aymane@buzzchat.com")
      .dateDeNaissance("26/02/2002")
      .prenom("Aymane")
      .nom("Menfaa")
      .photo("assets/photo.png");

    private UserCredentialsDTO user2 = new UserCredentialsDTO()
      .login("hamza")
      .password("pwd")
      .email("hamza@buzzchat.com")
      .dateDeNaissance("26/02/2002")
      .prenom("Hamza")
      .nom("Azer")
      .photo("assets/photo.png");



  @BeforeEach
  public void init () {
    MonCookie = new MonCookieJar();

    // Simulate the behavior of a web browser by remembering cookies set by the server
    OkHttpClient.Builder builder = new OkHttpClient.Builder();
    OkHttpClient okHttpClient = builder.cookieJar(MonCookie).build();
    ApiClient apiClient = new ApiClient(okHttpClient);
    apiAuth.setApiClient(apiClient);
    api.setApiClient(apiClient);


  }


    /**
     * Idem, pour ce test là en le testant manuellement ça marche
     * Mais avec mvn test, il ne passe pas (bizarre)
     *
     */
    @Test
    public void getUserNameTest() throws ApiException {
        apiAuth.signin(user1);
        String response = api.getUserName();
        assertEquals("aymane", response);
        apiAuth.signout();
    }


}
