/*
 * Buzzchat CPOO Server API
 * This is a prototype of CPOO's BuzzChat front/back API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: aymane.menfaa@insa-rennes.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.Gson;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Model tests for AddConversationRequest
 */
public class AddConversationRequestTest {
    private final AddConversationRequest model = new AddConversationRequest();

    /**
     * Model tests for AddConversationRequest
     */
    @Test
    public void testAddConversationRequest() {
      AddConversationRequest request = new AddConversationRequest();
      assertNotNull(request);
    }

    /**
     * Test the property 'logins'
     */
    @Test
    public void loginsTest() {
      List<String> logins = new ArrayList<>();
      logins.add("user1");
      logins.add("user2");

      AddConversationRequest request = new AddConversationRequest().logins(logins);

      assertNotNull(request.getLogins());
      assertEquals(logins, request.getLogins());
    }



}
